name: flet_code_editor_dsl
description: Flutter implementation of the flet-code-editor-dsl Flet extension.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flet: ^0.80.0
